const codeScrollContent = [
  { class: "code-line", indent: "", content: '&lt;html lang="en"&gt;' },
  { class: "code-line", indent: "indent", content: "&lt;head&gt;" },
  {
    class: "code-line",
    indent: "indent2",
    content: "&lt;title&gt;Portfolio&lt;/title&gt;",
  },
  { class: "code-line", indent: "indent", content: "&lt;/head&gt;" },
  { class: "code-line", indent: "indent", content: "&lt;body&gt;" },
  { class: "code-line", indent: "indent2", content: "const developer = {" },
  { class: "code-line", indent: "indent3", content: "name: 'Kyle'," },
  {
    class: "code-line",
    indent: "indent3",
    content: "skills: ['HTML5', 'CSS3', 'LEGOS'],",
  },
  { class: "code-line", indent: "indent3", content: "passion: 'clean code'" },
  { class: "code-line", indent: "indent2", content: "};" },
  {
    class: "code-line",
    indent: "indent2",
    content: "// TODO: Fix this later (famous last words)",
  },
  { class: "code-line", indent: "indent2", content: "function createUI() {" },
  { class: "code-line", indent: "indent3", content: "return responsive;" },
  { class: "code-line", indent: "indent2", content: "}" },
  {
    class: "code-line",
    indent: "indent2",
    content: "console.log('Why do programmers prefer dark mode?');",
  },
  { class: "code-line", indent: "indent2", content: ".hero-section {" },
  { class: "code-line", indent: "indent3", content: "display: flex;" },
  { class: "code-line", indent: "indent3", content: "min-height: 100vh;" },
  { class: "code-line", indent: "indent2", content: "}" },
  {
    class: "code-line",
    indent: "indent2",
    content: "// Because light attracts bugs! 🐛",
  },
  { class: "code-line", indent: "indent2", content: "if (user.experience) {" },
  { class: "code-line", indent: "indent3", content: "portfolio.showcase();" },
  { class: "code-line", indent: "indent2", content: "}" },
  {
    class: "code-line",
    indent: "indent2",
    content: "const legoLover = 'I LOVE LEGOS!!!';",
  },
  { class: "code-line", indent: "indent2", content: "class Designer {" },
  { class: "code-line", indent: "indent3", content: "constructor() {" },
  { class: "code-line", indent: "indent4", content: "this.creative = true;" },
  {
    class: "code-line",
    indent: "indent4",
    content: "this.debugMode = 'always';",
  },
  { class: "code-line", indent: "indent3", content: "}" },
  { class: "code-line", indent: "indent2", content: "}" },
  {
    class: "code-line",
    indent: "indent2",
    content: "// Works on my machine ¯\\_(ツ)_/¯",
  },
  {
    class: "code-line",
    indent: "indent2",
    content: "@media (max-width: 768px) {",
  },
  {
    class: "code-line",
    indent: "indent3",
    content: ".container { width: 100%; }",
  },
  { class: "code-line", indent: "indent2", content: "}" },
  {
    class: "code-line",
    indent: "indent2",
    content: "const isItWorking = Math.random() > 0.5;",
  },
  { class: "code-line", indent: "indent2", content: "fetch('/api/projects')" },
  {
    class: "code-line",
    indent: "indent3",
    content: ".then(res =&gt; res.json())",
  },
  {
    class: "code-line",
    indent: "indent3",
    content: ".then(data =&gt; render(data));",
  },
  {
    class: "code-line",
    indent: "indent2",
    content: "const express = require('express');",
  },
  { class: "code-line", indent: "indent2", content: "// Server goes brrrr" },
  { class: "code-line", indent: "indent2", content: "const app = express();" },
  {
    class: "code-line",
    indent: "indent3",
    content: "app.use(express.json());",
  },
  { class: "code-line", indent: "indent2", content: "app.listen(3000);" },
  {
    class: "code-line",
    indent: "indent2",
    content: "console.log('🚀 Houston, we have liftoff!');",
  },
  {
    class: "code-line",
    indent: "indent2",
    content: "import React from 'react';",
  },
  {
    class: "code-line",
    indent: "indent2",
    content: "import { useState, useEffect } from 'react';",
  },
  { class: "code-line", indent: "indent2", content: "// Hooks are magic ✨" },
  {
    class: "code-line",
    indent: "indent2",
    content: "const [active, setActive] = ",
  },
  { class: "code-line", indent: "indent3", content: "useState(false);" },
  {
    class: "code-line",
    indent: "indent2",
    content: "const bugCount = 0; // Narrator: There were bugs",
  },
];
